import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Influencers Validation",
  description: "Generated by Dr Aukanaw",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Influencers Validation</title>
      <meta
        name="description"
        content="Validation of health claims of influencers and celebrities"
      />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className="bg-white pl-[calc(100vw-100%)] text-black antialiased dark:bg-gray-950 dark:text-white">
        <main className="mb-auto">{children}</main>
      </body>
    </html>
  );
}
